### ISSUE TITLE
Primary backport checklist

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/interactive-template#23]
- [x] Docs should not include suggestions
- [x] Sheet columns can by typed (e.g. `columnName:number` or `person:string`
- [x] Better cron tasks
- [ ] SystemD config
- [x] Don't require creds for publish (in cases of AWS roles on EC2 machines)
- [x] ArchieML enhancements?
- [x] Parallelize API requests for sheets within a workbook (from elections20-primaries)
